image: Visual Studio 2017
clone_depth: 1
environment:
  IDASDK_URL:
    secure: MHF3svU4MYnjCrSis0ItrL4J3AIopO1Wk3+Mq7w5aiI=
  NINJA_URL:
    https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip
build_script:
- cmd: >-
    git submodule update --init --recursive

    REM extract idasdk70

    appveyor DownloadFile -FileName idasdk70.zip %IDASDK_URL%

    7z x idasdk70.zip -oC:\ >nul

    appveyor DownloadFile %NINJA_URL% -FileName ninja-win.zip

    7z x ninja-win.zip -oC:\ninja >nul

    set PATH=C:\ninja;%PATH%

    ninja --version

    REM visual studio

    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    mkdir build-7.0

    pushd build-7.0

    set IS64=True

    cmake .. -DCMAKE_PREFIX_PATH=C:\Qt\5.6.3\msvc2015_64 -DPYTHON_EXECUTABLE=C:/Python27-x64/python.exe -DIDA_EA_64=%IS64% -DIDA_BINARY_64=True -DIDA_SDK=C:\idasdk70 -DIDA_VERSION=700 -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja

    ninja

    set IS64=False

    cmake .. -DCMAKE_PREFIX_PATH=C:\Qt\5.6.3\msvc2015_64 -DPYTHON_EXECUTABLE=C:/Python27-x64/python.exe -DIDA_EA_64=%IS64% -DIDA_BINARY_64=True -DIDA_SDK=C:\idasdk70 -DIDA_VERSION=700 -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja

    ninja

    cd ..
artifacts:
- path: build-7.0\palette\ida_palette.dll
  name: IDA 7.0 EA32
- path: build-7.0\palette\ida_palette64.dll
  name: IDA 7.0 EA64